### ISSUE TITLE
Arguments in stub file?

### ISSUE THREAD

**Issue by skiano** [skiano/teamjam#3]
When the stub file is created after joining, shouldn't there be stub arguments if the test is passing anything in?

So if your solution looks like:

```javascript
exports.solution = (n) => n + 1
```

Right now your stub file generates:

```javascript
exports.solution = () => {
// your solution here...
}
```

But I think it should know the signature of the real solution and do:

```javascript
exports.solution = (n) => {
// your solution here...
}
```

What is the easiest way to get them in without resorting to some AST magic?

**Comment by tizmagik** [comment]
What about something like:

```js
exports.solution = ({ input }) => {
  // ...
}
```

Or is that just moving the problem? Maybe it should always just take a single argument, `input`?

**Comment by skiano** [comment]
Hmm, I think that just moves the problem, because is it good to assume you have no tests with 0 inputs?

It may be a good way to like get through it if it gets hard to just say your tests always have one input, but I'm hoping we could avoid that :)

**Comment by tizmagik** [comment]
I guess what are the cases where there would be no input?

**Comment by skiano** [comment]
I guess I cant think of any, but I like the solution you made, and even if there is only one, it's pretty cool that it can be a specific identifier name chosen by the test author. :)
